import { StyleSheet } from 'react-native';

export default Style = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#1f1f1f',
      alignItems: 'center',
      justifyContent: 'center',
    },
    viewInput: {
        padding:20,
        borderRadius: 10,
        height: 60,
        width:300,
        flexDirection: 'row',
        backgroundColor: '#373737',
        alignItems: 'center',
        paddingHorizontal: 10,
      },
    input: {
        color: '#fff',
        fontSize: 18,
        height: 60,
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        flex: 1,
      },
    texto: {
        color: "#fff", 
        textAlign: 'center', 
        fontWeight: 'bold',
        fontSize: 15,
        paddingBottom: 10,
    },
    botao: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        paddingHorizontal: 32,
        borderRadius: 10,
        elavation: 3,
        backgroundColor: '#b749e3',
        marginTop: 10,
        height: 60,
        width: 300,
      },
      botaoLimpar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        paddingHorizontal: 32,
        borderRadius: 10,
        elavation: 3,
        backgroundColor: '#373737',
        marginTop: 10,
        height: 60,
        width: 300,
      },
      botaoResultado: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 12,
        paddingHorizontal: 32,
        borderRadius: 10,
        elavation: 3,
        backgroundColor: 'white',
        marginTop: 10,
        height: 60,
        width: 300,
      },
  });